blender_version_min = "4.2.0"
id = "quick_interpolation"
license = ["SPDX:GPL-3.0-or-later",]
maintainer = "Austin Egge <austinegge@gmail.com>"
name = "Quick Interpolation"
schema_version = "1.0.0"
tagline = "Easily apply texture interpolation settings across textures"
type = "add-on"
version = "1.0.0"
website = "https://github.com/austinegge/quick_interpolation"
copyright = ["2024 Austin Egge",]
tags = ["Material", "User Interface"]
platforms = ["windows-x64", "macos-arm64", "macos-x64", "linux-x64"]
